import React from "react";

import Head from "next/head";
import Image from "next/image";
// import styles from "styles/Home.module.css";

const HomePage = (props) => {
  // console.log(props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* {props.insightResults &&
          props.insightResults.map((insightResult, idx) => (
            <div key={idx}>{insightResult.requestedUrl}</div>
          ))} */}
      </main>
    </div>
  );
};

export default HomePage;
