import React from "react";
import Head from "next/head";
import Link from "next/link";

import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Typography from "@mui/material/Typography";

const Sites = (props) => {
  const { sites } = props;

  return (
    <div>
      <Head>
        <title>View Sites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Box sx={{ flexGrow: 1 }}>
          <Grid container spacing={2} columns={12}>
            {sites &&
              sites.map(
                (site, idx) =>
                  !site.parentId && (
                    <Grid item xs={12} md={4} key={idx}>
                      <Link
                        href={`site/${site.name
                          .toLowerCase()
                          .replace(/ /g, "-")}`}
                        passHref
                      >
                        <a>
                          <div className="site-wrapper">
                            <Typography
                              noWrap
                              variant="h6"
                              gutterBottom
                              component="div"
                            >
                              {site.name}
                            </Typography>
                            {site.requestedUrl}
                            <br />
                            {site._id}
                          </div>
                        </a>
                      </Link>
                    </Grid>
                  )
              )}
          </Grid>
        </Box>
      </main>
    </div>
  );
};

export default Sites;
